### ISSUE TITLE
Fix the permit signature

### ISSUE THREAD

**Issue by amonsosanz** [0xPolygonHermez/zkevm-bridge-ui#232]
## Summary of Bug

Currently, it's not possible to deposit tokens as `UNI` that do not follow the EIP-2612. Uniswap removes the field `version` from the domain separator, so the signature must be computed differently.

We can do as Uniswap and [hardcode a list of tokens](https://github.com/Uniswap/widgets/blob/main/src/hooks/usePermit.ts#L28) per chain, or we can call the contract of the token to guess what type of permit does it implement and then compute the signature accordingly.

To do so we can read the value of [`PERMIT_TYPEHASH`](https://etherscan.io/address/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984#readContract#F3) and if it's not of [Dai type](https://github.com/yashnaman/tokensWithPermitFunctionList), then read [`DOMAIN_TYPEHASH`](https://etherscan.io/address/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984#readContract#F2) or [`EIP712DOMAIN_HASH`](https://etherscan.io/token/0xEEF9f339514298C6A857EfCfC1A762aF84438dEE#readContract#F1) as a fallback for `EIP-2612`.

### Steps to Reproduce

Try depositing UNI from L1 from an account that has not been approved with allowance.

**Comment by jesusholoo** [comment]
Just to complete the issue:
- The steps to calculate the signature will be:
- FIrst check the [`PERMIT_TYPEHASH`](https://etherscan.io/address/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984#readContract#F3)`
  - In case is  [`0xea2aa0a1be11a07ed86d755c93467f4f82362b452371d1ba94d1715123511acb`](https://etherscan.io/address/0x6b175474e89094c44da98b954eedeac495271d0f#code) Means in xDAi type, and the permit parameters will be: `keccak256("Permit(address holder,address spender,uint256 nonce,uint256 expiry,bool allowed)");`
  And the Domain will be `EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)`
  - In other case will be [` 0x6e71edae12b1b97f4d1f60370fef10105fa2faae0126114a169c64845d6126c9`](https://github.com/aragon/aragon-network-token/blob/3b6bfcb7068f99e0d67ac9cf2e3115ac0d13c63a/packages/v2/contracts/ANTv2.sol#L23) , and the permit parameters will be: `keccak256("Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)")`

  Then we need to check the `Domain_Typehash ` in order to difference the standarEIP (ours) form the uniswap type one:
  - In order to do this, since there's no standar for this we will need to ask for both `DOMAIN_TYPEHASH` or `EIP712DOMAIN_HASH`. One of the calls will revert and other one will return a bytes32.
      -  In case is  [`0x8b73c3c69bb8fe3d512ecc4cf759cc79239f7b179b0ffacaa9a75d522b39400f`] means that we are in our actually implementation type which the domain is calcualted as `keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)")`
      - In other case will be `0x8cad95687ba82c2ce50e74f7b754645e5117c3a5bec8151c0726d5857980a866` which is calculated by;`keccak256("EIP712Domain(string name,uint256 chainId,address verifyingContract)");`
